[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "fancy_rl"
version = "0.1.0"
dependencies = [
    "gymnasium",
    "pyyaml",
    "torch",
    "torchrl"
]
